name: deploy

on:
  push:
    branches: [master]

jobs:
  build:
    name: Install packages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Afrobank
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Checkout Core services
        uses: actions/checkout@v2
        with:
          path: packages/flex-core-services
          repository: Akinolae/afrobank-sdk
          token: ${{ secrets.GIT_DEFAULT_ACCESSS_TOKEN }}
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: BUILD
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Deploy 🚀
        uses: rdarida/simple-github-pages-deploy-action@v1
        with:
          git-base-folder: "dist"
