name: deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: npm install 
        env:
          CI: true
        run: |
          rm -rf node_modules
          yarn install
          yarn run build
