name: deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Afrobank
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: yarn
          # cache-dependency-path: "Afrobank/yarn.lock"
      - run: yarn install
